---
title: "ps2b"
author: "Hamza Husain"
date: "11/19/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading packages}
library(pacman)
p_load(dplyr, tidyverse, readr, knitr, ggplot2, stargazer, here, data.table, janitor, foreign, haven, fastDummies, jtools, dotwhisker, kableExtra, Synth)
```

```{r Reading data}
dta_folder <- "~/Library/Mobile Documents/com~apple~CloudDocs/BerkeleyARE/SecondYear/Fall/are213/problem_sets/ps2b"
setwd(dta_folder)

df<- read_dta("traffic_safety2.dta") %>% 
  arrange(state,year) %>% 
  mutate(fat_pc = fatalities/population,
           ln_fat_pc = log(fat_pc),
           ln_tvmt_pc = log(totalvmt/population),
           ln_precip = log(precip),
           ln_rspeed = log(rural_speed), 
           ln_uspeed = log(urban_speed))

# epiDisplay::tab1(df$state)
# length(unique(df$state)) #49 states 
# sapply(df, class)
```

1.) 

a.) 

```{r 1a}
# epiDisplay::tab1(df$year)
# length(unique(df$year)) #23 years
# 
# browse <- df %>% 
#   select(year, state, primary)
# View(browse)

event_years <- df %>% #figuring out event year for each state
  select(year,state,primary) %>%
  group_by(state) %>% 
  mutate(event = primary - lag(primary)) %>% 
  mutate(event = ifelse(is.na(event), 0, event)) %>% 
  filter(event == 1) %>% 
  select(-primary, -event) %>% 
  rename(event_year = year)
  
df_1a <- left_join(df, event_years, by = "state") %>% #merging event year to original data
  mutate(j = year - event_year )%>% 
  mutate(j = ifelse(is.na(j), 99, j)) %>% 
  filter(state != 99)
  

epiDisplay::tab1(df_1a$j)

summary_j <- df_1a %>% #looking at min and max event times by state
  select(state, year, event_year, j) %>% 
  group_by(state) %>% 
  filter(j != 99) %>% 
  summarise(min_j = min(j), max_j = max(j))

min_j <- min(summary_j$min_j)
max_j <- max(summary_j$max_j)
j_order <- paste('j', min_j:max_j, sep='_')

df_1a <- fastDummies::dummy_cols(df_1a, select_columns = "j", remove_first_dummy = F) %>% 
  select(-j_99) %>%
  relocate(all_of(j_order), .after = unemploy)
#coding separate time indicator for each possible value of event time 

df_1a_reg <- df_1a %>% 
  select(year, state, ln_fat_pc, starts_with("j_")) %>% 
  mutate(year = factor(year), state = factor(state))

reg_1a <- lm(ln_fat_pc ~ ., df_1a_reg)
summary(reg_1a)
```

The regression omits the dummy variable j_19 to avoid multicollinearity issues! 

b.) 

```{r 1b: Regression}
df_1b_reg <- df_1a_reg %>% 
  select(-"j_-1")

reg_1b <- lm(ln_fat_pc ~ ., df_1b_reg)
summary(reg_1b)
```

```{r 1b: Plot of event study coefficients}
summ(reg_1b)

df_1b_dw <- broom::tidy(reg_1b) %>% 
  filter(grepl("j_", term))

j_coefplot <- dwplot(df_1b_dw) + 
  theme(text = element_text(size = 6)) + 
  ggtitle("Event Study Coefficients")


j_coefplot
```

```{r 1c}

```


2.) Synthetic Control Problem 

i.)
```{r 2ai}
df_2a <-  left_join(df, event_years, by = "state") %>% #merging event year to original data
  mutate(j = year - event_year )%>% 
  mutate(j = ifelse(is.na(j), 99, j))

df_2a_i_TU <- df_2a %>% 
  filter(state == 99 & j < 0) %>% 
  select(state, year, ln_fat_pc) %>% 
  mutate(state = "TU")

df_2a_i_control <- df_2a %>% 
  filter(j == 99) %>% 
  filter(year %in% (1981:1985)) %>% 
  select(state, year, ln_fat_pc) %>% 
  group_by(year) %>% 
  summarise(ln_fat_pc = mean(ln_fat_pc)) %>% 
  mutate(state = "average control") %>% 
  relocate(state)


df_2a_i_both <- rbind(df_2a_i_control, df_2a_i_TU)

graph_2a_i <- ggplot(df_2a_i_both, 
                     aes(year, ln_fat_pc, 
                     group = factor(state), 
                     color = factor(state))) + 
  geom_line() + 
  geom_point() +
  ggtitle("Pre-period Log Traffic Fatalities")

graph_2a_i
```

ii.) 

```{r 2aii_1}
df_2a_ii_control <- df_2a %>% 
  filter(j == 99) %>% 
  filter(year %in% (1981:1985)) %>% 
  select(state, year, ln_fat_pc) %>% 
  filter(year == 1985)

df_2a_ii_TU <- df_2a %>% 
  filter(state == 99 & j < 0) %>% 
  select(state, year, ln_fat_pc) %>% 
  mutate(state = "TU") %>% 
  filter(year == 1985) %>% 
  rename(ln_fat_pc_TU = ln_fat_pc) %>% 
  select(-state)

df_2a_ii <- left_join(df_2a_ii_control, df_2a_ii_TU, by = "year") %>% 
  mutate(diff_ln_fat_pc = abs(ln_fat_pc - ln_fat_pc_TU)) %>% 
  arrange(diff_ln_fat_pc)

```

WV best matches the TU. 

```{r 2aii_2}
df_2a_ii_2 <- df %>% 
  filter(year == 1985 & (state == 47 | state == 99)) %>% 
  mutate(state = ifelse(state == 47, "WV", "TU")) %>%
  t() %>% 
  kbl() %>% 
  kable_classic(full_width = F, html_font = "Cambria")

df_2a_ii_2
```

However, the covariates seem very different between the two. 

b.) 

  i.) 
  
  ii.) 
  
```{r 2b}
df_2b <- df %>% 
  mutate(state_no = as.numeric(unlist(state)))

all_years <- df %>%
      arrange(year) %>%
      select(year) %>%
      unique()%>%
      unlist() %>%
      as.numeric(.)

# Create list of pre-treatment years
preperiod_years <- df %>%
    filter(state == 99, primary == 0) %>%
    select(year) %>%
    unlist(.) %>%
    as.numeric(.)

# Create list of control states
control_states <- df %>%
    group_by(state) %>%
    mutate(control = ifelse(mean(primary) > 0, 0, 1)) %>%
    filter(year == tail(preperiod_years, n=1)) %>%
    filter(control == 1) %>%
    select(state) %>%
    unlist(.) %>%
    as.numeric(.)

state_names <- rownames(data.frame(attr(df$state, 'label')))

    
predictors1 <- c("college" , "beer" , "unemploy" , "ln_tvmt_pc" , "ln_precip", "snow32")

dataprep.out <- dataprep(foo = data.frame(df_2b), 
                         predictors = predictors1, 
                         time.predictors.prior = preperiod_years, 
                         dependent = "ln_fat_pc", 
                         unit.variable = "state_no", 
                         time.variable = "year",
                         treatment.identifier = 99,
                         controls.identifier = control_states, 
                         time.optimize.ssr = preperiod_years,
                         time.plot = all_years)

synth.out <- synth(data.prep.obj = dataprep.out, method = "BFGS")

synth.tables <- synth.tab(dataprep.res = dataprep.out,
                           synth.res = synth.out)

synth.tables$tab.pred
                         
path.plot(synth.res = synth.out, dataprep.res = dataprep.out, 
           Ylab = "log(Traffic Fatalities per Captia)",
           Xlab = "year",
           Ylim = c(-2,-1),
           Legend = c("Aggregate Treatment State","Synthetic Control State"),
           Main = "Traffic Fatalities before and after Primary Seat Belt Laws",
           tr.intake = tail(preperiod_years, n=1)+1)    

gaps.plot(synth.res = synth.out, dataprep.res = dataprep.out)

```
  














